// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  GetApiAdminPostsData,
  GetApiAdminPostsResponses,
  GetApiAdminStatsData,
  GetApiAdminStatsResponses,
  GetApiAdminUsersData,
  GetApiAdminUsersResponses,
  PostApiAdminPostsByIdRemoveData,
  PostApiAdminPostsByIdRemoveErrors,
  PostApiAdminPostsByIdRemoveResponses,
  PostApiAdminPostsByIdRestoreData,
  PostApiAdminPostsByIdRestoreErrors,
  PostApiAdminPostsByIdRestoreResponses,
  PostApiAdminUsersByIdSuspendData,
  PostApiAdminUsersByIdSuspendErrors,
  PostApiAdminUsersByIdSuspendResponses,
  PostApiAdminUsersByIdUnsuspendData,
  PostApiAdminUsersByIdUnsuspendErrors,
  PostApiAdminUsersByIdUnsuspendResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Search users by username or email
 */
export const getApiAdminUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminUsersData, ThrowOnError>,
): RequestResult<GetApiAdminUsersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminUsersResponses, unknown, ThrowOnError>({
    url: "/api/admin/users",
    ...options,
  })

/**
 * Suspend a user site-wide
 */
export const postApiAdminUsersByIdSuspend = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminUsersByIdSuspendData, ThrowOnError>,
): RequestResult<
  PostApiAdminUsersByIdSuspendResponses,
  PostApiAdminUsersByIdSuspendErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminUsersByIdSuspendResponses,
    PostApiAdminUsersByIdSuspendErrors,
    ThrowOnError
  >({
    url: "/api/admin/users/{id}/suspend",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Lift a user's suspension
 */
export const postApiAdminUsersByIdUnsuspend = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminUsersByIdUnsuspendData, ThrowOnError>,
): RequestResult<
  PostApiAdminUsersByIdUnsuspendResponses,
  PostApiAdminUsersByIdUnsuspendErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminUsersByIdUnsuspendResponses,
    PostApiAdminUsersByIdUnsuspendErrors,
    ThrowOnError
  >({ url: "/api/admin/users/{id}/unsuspend", ...options })

/**
 * Search posts by title (includes removed posts)
 */
export const getApiAdminPosts = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminPostsData, ThrowOnError>,
): RequestResult<GetApiAdminPostsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminPostsResponses, unknown, ThrowOnError>({
    url: "/api/admin/posts",
    ...options,
  })

/**
 * Remove a post site-wide (admin)
 */
export const postApiAdminPostsByIdRemove = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminPostsByIdRemoveData, ThrowOnError>,
): RequestResult<
  PostApiAdminPostsByIdRemoveResponses,
  PostApiAdminPostsByIdRemoveErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminPostsByIdRemoveResponses,
    PostApiAdminPostsByIdRemoveErrors,
    ThrowOnError
  >({ url: "/api/admin/posts/{id}/remove", ...options })

/**
 * Restore a removed post site-wide (admin)
 */
export const postApiAdminPostsByIdRestore = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminPostsByIdRestoreData, ThrowOnError>,
): RequestResult<
  PostApiAdminPostsByIdRestoreResponses,
  PostApiAdminPostsByIdRestoreErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminPostsByIdRestoreResponses,
    PostApiAdminPostsByIdRestoreErrors,
    ThrowOnError
  >({ url: "/api/admin/posts/{id}/restore", ...options })

/**
 * Site-wide counts overview
 */
export const getApiAdminStats = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminStatsData, ThrowOnError>,
): RequestResult<GetApiAdminStatsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminStatsResponses, unknown, ThrowOnError>({
    url: "/api/admin/stats",
    ...options,
  })
