// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  getApiAdminPosts,
  getApiAdminStats,
  getApiAdminUsers,
  type Options,
  postApiAdminPostsByIdRemove,
  postApiAdminPostsByIdRestore,
  postApiAdminUsersByIdSuspend,
  postApiAdminUsersByIdUnsuspend,
} from "../sdk.gen"
import type {
  GetApiAdminPostsData,
  GetApiAdminPostsResponse,
  GetApiAdminStatsData,
  GetApiAdminStatsResponse,
  GetApiAdminUsersData,
  GetApiAdminUsersResponse,
  PostApiAdminPostsByIdRemoveData,
  PostApiAdminPostsByIdRemoveError,
  PostApiAdminPostsByIdRemoveResponse,
  PostApiAdminPostsByIdRestoreData,
  PostApiAdminPostsByIdRestoreError,
  PostApiAdminPostsByIdRestoreResponse,
  PostApiAdminUsersByIdSuspendData,
  PostApiAdminUsersByIdSuspendError,
  PostApiAdminUsersByIdSuspendResponse,
  PostApiAdminUsersByIdUnsuspendData,
  PostApiAdminUsersByIdUnsuspendError,
  PostApiAdminUsersByIdUnsuspendResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getApiAdminUsersQueryKey = (options?: Options<GetApiAdminUsersData>) =>
  createQueryKey("getApiAdminUsers", options)

/**
 * Search users by username or email
 */
export const getApiAdminUsersOptions = (options?: Options<GetApiAdminUsersData>) =>
  queryOptions<
    GetApiAdminUsersResponse,
    DefaultError,
    GetApiAdminUsersResponse,
    ReturnType<typeof getApiAdminUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAdminUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAdminUsersQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const getApiAdminUsersInfiniteQueryKey = (
  options?: Options<GetApiAdminUsersData>,
): QueryKey<Options<GetApiAdminUsersData>> => createQueryKey("getApiAdminUsers", options, true)

/**
 * Search users by username or email
 */
export const getApiAdminUsersInfiniteOptions = (options?: Options<GetApiAdminUsersData>) => {
  const opts = infiniteQueryOptions<
    GetApiAdminUsersResponse,
    DefaultError,
    InfiniteData<GetApiAdminUsersResponse>,
    QueryKey<Options<GetApiAdminUsersData>>,
    string | Pick<QueryKey<Options<GetApiAdminUsersData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiAdminUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiAdminUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiAdminUsersInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * Suspend a user site-wide
 */
export const postApiAdminUsersByIdSuspendMutation = (
  options?: Partial<Options<PostApiAdminUsersByIdSuspendData>>,
): UseMutationOptions<
  PostApiAdminUsersByIdSuspendResponse,
  PostApiAdminUsersByIdSuspendError,
  Options<PostApiAdminUsersByIdSuspendData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAdminUsersByIdSuspendResponse,
    PostApiAdminUsersByIdSuspendError,
    Options<PostApiAdminUsersByIdSuspendData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAdminUsersByIdSuspend({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Lift a user's suspension
 */
export const postApiAdminUsersByIdUnsuspendMutation = (
  options?: Partial<Options<PostApiAdminUsersByIdUnsuspendData>>,
): UseMutationOptions<
  PostApiAdminUsersByIdUnsuspendResponse,
  PostApiAdminUsersByIdUnsuspendError,
  Options<PostApiAdminUsersByIdUnsuspendData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAdminUsersByIdUnsuspendResponse,
    PostApiAdminUsersByIdUnsuspendError,
    Options<PostApiAdminUsersByIdUnsuspendData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAdminUsersByIdUnsuspend({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAdminPostsQueryKey = (options?: Options<GetApiAdminPostsData>) =>
  createQueryKey("getApiAdminPosts", options)

/**
 * Search posts by title (includes removed posts)
 */
export const getApiAdminPostsOptions = (options?: Options<GetApiAdminPostsData>) =>
  queryOptions<
    GetApiAdminPostsResponse,
    DefaultError,
    GetApiAdminPostsResponse,
    ReturnType<typeof getApiAdminPostsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAdminPosts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAdminPostsQueryKey(options),
  })

export const getApiAdminPostsInfiniteQueryKey = (
  options?: Options<GetApiAdminPostsData>,
): QueryKey<Options<GetApiAdminPostsData>> => createQueryKey("getApiAdminPosts", options, true)

/**
 * Search posts by title (includes removed posts)
 */
export const getApiAdminPostsInfiniteOptions = (options?: Options<GetApiAdminPostsData>) => {
  const opts = infiniteQueryOptions<
    GetApiAdminPostsResponse,
    DefaultError,
    InfiniteData<GetApiAdminPostsResponse>,
    QueryKey<Options<GetApiAdminPostsData>>,
    string | Pick<QueryKey<Options<GetApiAdminPostsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiAdminPostsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiAdminPosts({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiAdminPostsInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * Remove a post site-wide (admin)
 */
export const postApiAdminPostsByIdRemoveMutation = (
  options?: Partial<Options<PostApiAdminPostsByIdRemoveData>>,
): UseMutationOptions<
  PostApiAdminPostsByIdRemoveResponse,
  PostApiAdminPostsByIdRemoveError,
  Options<PostApiAdminPostsByIdRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAdminPostsByIdRemoveResponse,
    PostApiAdminPostsByIdRemoveError,
    Options<PostApiAdminPostsByIdRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAdminPostsByIdRemove({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Restore a removed post site-wide (admin)
 */
export const postApiAdminPostsByIdRestoreMutation = (
  options?: Partial<Options<PostApiAdminPostsByIdRestoreData>>,
): UseMutationOptions<
  PostApiAdminPostsByIdRestoreResponse,
  PostApiAdminPostsByIdRestoreError,
  Options<PostApiAdminPostsByIdRestoreData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAdminPostsByIdRestoreResponse,
    PostApiAdminPostsByIdRestoreError,
    Options<PostApiAdminPostsByIdRestoreData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAdminPostsByIdRestore({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAdminStatsQueryKey = (options?: Options<GetApiAdminStatsData>) =>
  createQueryKey("getApiAdminStats", options)

/**
 * Site-wide counts overview
 */
export const getApiAdminStatsOptions = (options?: Options<GetApiAdminStatsData>) =>
  queryOptions<
    GetApiAdminStatsResponse,
    DefaultError,
    GetApiAdminStatsResponse,
    ReturnType<typeof getApiAdminStatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAdminStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAdminStatsQueryKey(options),
  })
